### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by kdaust** [FLNRO-Smithers-Research/ByBecApp#7]
- [x] Update "add offsite" to be more form like; dropdown for necessary parts
- [x] Colour offsite trials by assessment level
- [x] Find a BGC - add option to select by zone
- [x] Forest health - when a new species or pest is selected, collapse table at bottom of map
- [ ] Offsite - show labels without having to click
